#!/usr/bin/env bash

libname="lib${1}"

cat > ${libname}.c <<EOF
#include "./src/lua5.4/lua.h"
#include "./src/lua5.4/lauxlib.h"
#include "./src/N2DE/N2DE.h"

luaL_Reg ${libname}[] = {
    {NULL, NULL}
};

int luaopen_extensions_${libname}(lua_State *L)
{
    luaL_newlib(L, ${libname});
    return 1;
}
EOF
